import { Geist, Geist_Mono, DM_Serif_Display, Mrs_Saint_Delafield } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/ui/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const Serif_Display = DM_Serif_Display({
  variable: "--font-serif",
  weight: '400',
  subsets: ["latin"],
});

const signature = Mrs_Saint_Delafield({
  variable: "--font-signature",
  weight: '400',
  subsets: ["latin"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${Serif_Display.variable} ${signature.variable} antialiased`}
        >
        <Header/>
        {children}
      </body>
    </html>
  );
}
